### PR TITLE
changed searchCountries and changed api call

### PR DESCRIPTION
**Pull request by lukaasz555**

### CODE REVIEW

**Comment by iamzaidmohammed** [comment]
Oh okay. Now I'm getting the hang of it.
But the filter is still not working

**Comment by lukaasz555** [comment]
Probably 'cuz you are still using old hook setCountries inside filterCountries. Don't forget that now, you are rendering components based on FILTERED, not countries. Check this out & let me know.

**Comment by iamzaidmohammed** [comment]
Well I was a able to filter by the region but when I click on "All" nothing shows on the screen.

**Comment by lukaasz555** [comment]
Because your API call inside filterCountries() looks like:
fetch(`https://restcountries.com/v2/**region/${selectValue}**`)

If you want to get all countries you can change URL (when user pick All) or you can just setFiltered(allCountries).

**Comment by iamzaidmohammed** [comment]
Oh yhyh but I've changed it

**Comment by iamzaidmohammed** [comment]
Now it looks like this 
const filterCountries = (e) => {
    const selectValue = e.target.value.toLowerCase();
    console.log(selectValue);
    if (allCountries) {
      const filteredItems = allCountries.filter((item) =>
        item.region.toLowerCase().includes(selectValue)
      );
      setFiltered(filteredItems);
    }
  };

**Comment by lukaasz555** [comment]
It's easy, just add simple if, look:

	const filterCountries = (e) => {
		const selectValue = e.target.value.toLowerCase();
		console.log(selectValue);
		if (selectValue !== 'all') {
			const filteredItems = allCountries.filter((item) =>
				item.region.toLowerCase().includes(selectValue)
			);
			setFiltered(filteredItems);
		} else {
			setFiltered(allCountries);
		}
	};

**Comment by iamzaidmohammed** [comment]
Oh yeah. It works now

**Comment by iamzaidmohammed** [comment]
But there's a little bit problem. You see because the API call was changed now if the search query is not found, the not found component does not render.

**Comment by lukaasz555** [comment]
Show code pls

**Comment by iamzaidmohammed** [comment]
`  const notFound = countries.status || countries.message;

<div className="countries">
                {!notFound ? (
                  filtered.map((country) => {
                    return (
                      <Country
                        darkMode={darkMode}
                        key={country.alpha3Code}
                        code={country.alpha3Code}
                        name={country.name}
                        capital={country.capital}
                        population={country.population}
                        region={country.region}
                        flag={country.flag}
                        showDetails={showDetails}
                      />
                    );
                  })
                ) : (
                  <NotFound />
                )}
              </div>`

**Comment by iamzaidmohammed** [comment]
const notFound = countries.status || countries.message;

<div className="countries">
                {!notFound ? (
                  filtered.map((country) => {
                    return (
                      <Country
                        darkMode={darkMode}
                        key={country.alpha3Code}
                        code={country.alpha3Code}
                        name={country.name}
                        capital={country.capital}
                        population={country.population}
                        region={country.region}
                        flag={country.flag}
                        showDetails={showDetails}
                      />
                    );
                  })
                ) : (
                  <NotFound />
                )}
              </div>

**Comment by lukaasz555** [comment]
Hmm, it's not best way to handling errors. You can use useState hook, e.g.
const [error, setError] = useState<boolean>(false);

Then you can modify func, sth like:

	const searchCountries = (e) => {
		const inputValue = e.target.value.toLowerCase();
		if (allCountries.length > 0) {
			const filteredItems = allCountries.filter((item) =>
				item.name.toLowerCase().includes(inputValue)
			);
			if (filteredItems.length > 0) {
				setError(false);
				setFiltered(filteredItems);
			} else if (filteredItems.length === 0 && inputValue !== '') {
				setError(true);
			} else if (inputValue === '') {
				setError(false);
				setFiltered(allCountries);
			}
		}
	};

**Comment by lukaasz555** [comment]
And JSX looks like this:

`<div className='countries'>
								{!error ? (
									filtered.map((country) => {
										return (
											<Country
												darkMode={darkMode}
												key={country.alpha3Code}
												code={country.alpha3Code}
												name={country.name}
												capital={country.capital}
												population={country.population}
												region={country.region}
												flag={country.flag}
												showDetails={showDetails}
											/>
										);
									})
								) : (
									<p>not found</p>
								)}
							</div>`

**Comment by lukaasz555** [comment]
You can check out YT channel Web Dev Simplified or Lama Dev. They show how to use react hooks in really nice and easy way.

**Comment by iamzaidmohammed** [comment]
Oh great. Now I thinks everything is working as it should

**Comment by iamzaidmohammed** [comment]
So how about we connect for future projects. I really love working with you😊

**Comment by lukaasz555** [comment]
Sure, let’s stay in touch:

https://pl.linkedin.com/in/%C5%82ukasz-zegar

Just text me at LI, I’ll try to help:)

W dniu śr., 30.11.2022 o 21:03 Zaid Mohammed Zainudeen <
***@***.***> napisał(a):

**Comment by iamzaidmohammed** [comment]
Okay

**Pull request merged**
